

- import_tasks: hostname.yml

- import_tasks: timezone.yml

- ansible.builtin.import_tasks: directories.yml

- ansible.builtin.import_tasks: users.yml

- ansible.builtin.import_tasks: sudo.yml

- ansible.builtin.import_tasks: ssh.yml

- ansible.builtin.import_tasks: modules.yml

- ansible.builtin.import_tasks: sysctl.yml

- ansible.builtin.import_tasks: limits.yml

- ansible.builtin.import_tasks: swap.yml

- ansible.builtin.include_tasks: firewall.yml

- name: Allow essential ports in UFW
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - '22'
    - '80'
    - '443'

- name: Enable UFW firewall with default deny incoming
  ufw:
    state: enabled
    policy: deny
    direction: incoming
