---
- import_tasks: install.yml
  tags:
    - traefik
    - traefik_install

- import_tasks: config.yml
  tags:
    - traefik
    - traefik_config

- import_tasks: service.yml
  tags:
    - traefik
    - traefik_service
