---
- name: Configure Bare Metal Ubuntu
  hosts: all
  become: true
  roles:
    - role: common
      tags: common
    - role: traefik
      tags: traefik
    - role: nexus
      tags: nexus
    - role: monitoring
      tags: monitoring
    - role: backup
      tags: backup
